### ISSUE TITLE
[FR] - add symlink in dockerfile to each entry in /nix/store

### ISSUE THREAD

**Issue by zenithpool** [IntersectMBO/cardano-node#1751]
*External*   

**Describe the feature you'd like**
To make the provided docker image `inputoutput/cardano-node` more extensible. It would be great if all the files/folders under `/nix/store` in the dockerfile were simplified. So instead of `/nix/store/3678ccikas3q16jcqcghwviqsd5k9wjx-mainnet-byron-genesis.json`, it could just be `/nix/store/mainnet-byron-genesis.json`. otherwise it is impossible to provide the filepath of the genesis files in the configuration file to make it work with future docker image updates

**Describe alternatives you've considered**
I tried to attach a custom genesis file through a configmap or secret in kubernetes but there is a limit on the size of a configmap of 1MB which the mainnet byron genesis file exceeds.

**Comment by magick93** [comment]
Thanks

Am having the same problem.

Would be nice if IOHK didnt use random directory names. I really dont understand why they would do this.
