### ISSUE TITLE
[BUG] - No error message when signing a transaction with the wrong amount of signing keys 

### ISSUE THREAD

**Issue by bahamasbahamas** [IntersectMBO/cardano-node#3309]
*External* 

**Area**
*Native Tokens*    Related to Native Tokens (Mary).

**Summary**
I described my problem on Cardano stackexchange. 

https://cardano.stackexchange.com/questions/4149/scriptwitnessnotvalidatingutxow-error-when-submitting-transaction

Basically I was trying to submit a transaction with the cardano-cli.
The transaction includes a policy for token minting.  

**Steps to reproduce**
1. build a raw transaction with cardano-cli
the transaction should include important stuff for simple transaction and should include all the necessary information for token minting
2. sign transaction only with your payment.skey
3. submit the transaction 
4. you will get an ScriptWitnessNotValidatingUTXOW error, but you would have no idea why

**Expected behavior**
When signing a transaction with wrong amount of signing keys you should see an error like: not the right amount of signing keys for signing this raw transaction.  

**System info (please complete the following information):**
- OS Name:  Ubuntu
- OS Version 20.04
- Node version 1.30.1

**Comment by mplomin** [comment]
You only signed with one signing key.

cardano-cli transaction sign \
--tx-body-file keys/nfttx.raw  \
--signing-key-file keys/payment.skey \
****missing second signature for the policy key*****
--mainnet  \
--out-file keys/tx.signed
