### ISSUE TITLE
db-analyser: refactor and move

### ISSUE THREAD

**Issue by deepfire** [IntersectMBO/cardano-node#3974]
* Move the `db-analyser` tool from https://github.com/input-output-hk/ouroboros-network/tree/master/ouroboros-consensus-cardano/tools to the new project `db-synthesizer` lives in (cf. #3852).
* Refactor the analyser into a library / API and an executable part.
* Ideally, refactor into a common library for both `db-analyser` and `db-synthesizer` and seperate executables.
* Beware: Once UTxO-HD lands, there'll be a big rewrite of the `Analysis.hs` module.

**Comment by mgmeier** [comment]
Refactor and move completed: `db-analyser` and `db-synthesizer` have now a common library and API and seperate executables.

The corresponding PR to eventually land the project in `master`: https://github.com/input-output-hk/ouroboros-network/pull/3817
