### ISSUE TITLE
cardano-tracer: configurable addition of prefixes for metrics

### ISSUE THREAD

**Issue by deepfire** [IntersectMBO/cardano-node#3988]
We are removing the `Cardano.Node` namespace prefix from all traces in `cardano-node`.

This will impact metric names.

We'd like to allow users to continue using old metric names: https://github.com/input-output-hk/cardano-node/issues/3978

An easy way for this would be to append a configurable fixed string prefix for Prometheus exports.

**Comment by mgmeier** [comment]
Resolved with #5905. The optional node config value `TraceOptionMetricsPrefix` (String) has been added for that purpose.
