### ISSUE TITLE
workbench:  integrate UTxO HD-capable version of the node

### ISSUE THREAD

**Issue by deepfire** [IntersectMBO/cardano-node#4001]
This will allow us to run various benchmarking profiles against it.

We need:

1. a node version with the HD storage capability
2. basic instructions on how to control functionality in the node

**Comment by Jasagredo** [comment]
We are using the following versions that can be used to run benchmarks:
- [`consensus/feature/utxo-hd`](https://github.com/input-output-hk/cardano-node/tree/consensus/feature/utxo-hd): 470d2131327722fe607c49288beed90576848969
    - Which uses [`ouroboros-network@feature/utxo-hd`](https://github.com/input-output-hk/ouroboros-network/tree/feature/utxo-hd) at current commit [09cd230](https://github.com/input-output-hk/ouroboros-network/commit/09cd230888c0c2a69d6848d7204911fc4844d5d8)
- [`consensus/feature/utxo-hd-baseline`](https://github.com/input-output-hk/cardano-node/tree/consensus/feature/utxo-hd-baseline) 2b2d5dd4e2c349c6075f8abb338bce1911d09fe0 (equivalent to master as of the moment of writing this comment)
    - Which uses ouroboros-network@c254d02b9de67cabc71d26e3f27a2a3d13538d21, the one already pointed to by `cardano-node@master`

As for instructions, the UTxO-HD node should be equivalent to a normal node except for the following points:
1. `liblmdb` has to be in the system. I installed it globally with `sudo apt install liblmdb-dev` but if you are using Nix you might need to add it to `buildInputs` or some such.
2. There are two new environment variables which is not ideal and will be ported to configuration flags:
    - `DISABLE_DUAL_LEDGER=True` has to be set to True always. This will just go away eventually.
    - `BACKEND=(LMDB|MEM)` one of those two. In principle SPOs will run with `MEM` and normal users with `LMDB`, so both would need to be benchmarked

**Comment by Jasagredo** [comment]
I might push some changes to `consensus/feature/utxo-hd` today but I will just try to add lmdb to the CI, so they should be not a problem if you happen to get also those included, but otherwise, use the pointed 470d2131327722fe607c49288beed90576848969

**Comment by jasagredo** [comment]
This (and much more) was done since this issue was last looked at.
