### ISSUE TITLE
[BUG] - ```cardano-cli``` ```--tx-in-redeemer-value``` causes evalutaion error in UPLC programs

### ISSUE THREAD

**Issue by HarmonicPool** [IntersectMBO/cardano-node#4037]
*External* 

**Area**
*Plutus*    Related to Plutus Scripts (Alonzo).

**Summary**
A clear and specific description of what the bug is.

trying ot construct a transaction as follows
```bash
cardano-cli transaction build \
    --$testnet \
   ${other_tx_in} \
    --tx-in $scUtxoIn \
    --tx-in-script-file "testnet/validator.plutus.json" \
    --tx-in-datum-file "testnet/int1.json"  \
    --tx-in-redeemer-value "{\"constructor\":0,\"fields\": [] }" \
    --tx-in-collateral $utxoCollateral \
    \
    ${other_txlogic}
    --out-file "unsigned.tx"
```

causes
```
Command failed: transaction build  Error: The following scripts have execution failures:
the script for transaction input 1 (in the order of the TxIds) failed with: 
The Plutus script evaluation failed: An error has occurred:  User error:
The provided Plutus code called 'error'.
Caused by: [
  (builtin unConstrData)
  (con data #a24b636f6e7374727563746f7200466669656c647380)
]
```

I understood ```--tx-in-redeemer-value``` is the problem by deserializing the constant data ```#a24b636f6e7374727563746f7200466669656c647380``` as cbor

substituting that line with
```bash
--tx-in-redeemer-file "testnet/unit.json" \
```
where ```testnet/unit.json``` is:
```json
{"fields":[],"constructor":0}
```
solves the issue 

**Steps to reproduce**
Steps to reproduce the behaviour:
1. get a serialized validator script that accepts units (```()```) as redeemers
2. construct a transaction specifing the script, the datum that matches the one sitting on the script when hashed and a redeemer by using ```--tx-in-redeemer-value "{\"constructor\":0,\"fields\": [] }"```

**Expected behaviour**

```--tx-in-redeemer-value``` works just like ```--tx-in-redeemer-file``` on same content

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 20.04
- Node version (output of `cardano-node --version`) : ```1.33.0```
- CLI version  (output of `cardano-cli --version`): ```1.33.0```

**Comment by CarlosLopezDeLara** [comment]
Closing as per @james-iohk comment above. `--tx-in-redeemer-value` takes only builtin types
