### ISSUE TITLE
[BUG] - cardano-node metrics: missing some gc stats on FreeBSD

### ISSUE THREAD

**Issue by reqlez** [IntersectMBO/cardano-node#4190]
**External**

*Other*

**Summary**
On FreeBSD, some GC-related metrics are always showing "0". 
Not sure if this is cardano-node related or upstream ( ghc ).

**Steps to reproduce**
Install cardano-node on FreeBSD:
https://university.psilobyte.io/en/how-to/cardano-freebsd-relay-setup

curl localhost:12798/metrics

**Expected behavior**
FreeBSD ( not working ): 
cardano_node_metrics_RTS_gcHeapBytes_int 0
Ubuntu ( working ): 
cardano_node_metrics_RTS_gcHeapBytes_int 3244294144

**System info (please complete the following information):**
- OS Name: FreeBSD
- OS Version: 13.1
- Node version: cardano-node 1.35.1 - freebsd-x86_64 - ghc-8.10
git rev c75451f0ffd7a60b5ad6c4263891e6c8acac105a
- CLI version: cardano-cli 1.35.1 - freebsd-x86_64 - ghc-8.10
git rev c75451f0ffd7a60b5ad6c4263891e6c8acac105a

**Additional context**
Here are the fields i found that are not working:
cardano_node_metrics_RTS_gcticks_int 0
cardano_node_metrics_Mem_resident_int 0
cardano_node_metrics_RTS_gcHeapBytes_int 0
cardano_node_metrics_RTS_mutticks_int 0
cardano_node_metrics_RTS_gcMajorNum_int 0
cardano_node_metrics_RTS_gcMinorNum_int 0
cardano_node_metrics_Stat_cputicks_int 0
cardano_node_metrics_Stat_threads_int 0
cardano_node_metrics_RTS_gcLiveBytes_int 0

This is not critical, and I fully understand BSD is not officially supported, however it would be cool if fixed one day :)
I also wonder if there is a similar issue with Darwin or not...

**Comment by Jimbo4350** [comment]
Closing this. Please reopen if this is still relevant.

**Comment by reqlez** [comment]
@Jimbo4350 I built / ran master branch today with GHC 9.2.7 and the issue is still here.

**Comment by mgmeier** [comment]
I've tried to reproduce on Darwin (macOS Sonoma Version 14.6.1 x86_64). I could not detect any such issue with the metrics on Darwin. I doubt we can port the way resource usage is queried to FreeBSD directly, it uses `https://developer.apple.com/documentation/kernel/1537934-task_info`.

As for solving the issue, it seems FreeBSD is not supported even by the GHC team (anymore?) - please correct me if I'm wrong. If anyone has their development stack running on FreeBSD, and feels highly motivated, they'd need to provide a platform-specific implementation for
`readResourceStatsInternal`,
called from module
`Cardano.Logging.Resources`
in package
`trace-resources`.
