### ISSUE TITLE
Redesign of typed-protocols

### ISSUE THREAD

**Issue by coot** [IntersectMBO/cardano-node#4221]
Related pull requests:
* https://github.com/input-output-hk/typed-protocols/pull/3
* https://github.com/input-output-hk/ouroboros-network/pull/3675
* https://github.com/input-output-hk/cardano-node/pull/3845
* https://github.com/input-output-hk/ekg-forward/pull/5

**Comment by Jimbo4350** [comment]
Closing this. If this is still relevant please reopen.

**Comment by coot** [comment]
Still relevant, this is a longer work stream, and although it might appear stale it will be eventually merged.
