### ISSUE TITLE
[BUG] - Metadata ordering neither as in JSON input nor canonical

### ISSUE THREAD

**Issue by HeptaSean** [IntersectMBO/cardano-node#4335]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Summary**
When giving a `metadata.json` file to `cardano-cli transaction build`, the metadata in the resulting CBOR is ordered differently, but not canonically.

**Steps to reproduce**
1. Create a `metadata.json` with some keys neither in alphabetical nor in length-then-alphabetical order:
```
           […]
                "name": "HeptaSean's Card",
                "mediaType": "image/svg+xml",
                "image": […],
                "files": [
                    {
                        "mediaType": "text/html",
                        "src": […]
                    }
                ]
           […]
```
2. Build a transaction with this metadata using `cardano-cli transaction build`.
3. Look at the generated CBOR:
```
$ cardano-cli text-view decode-cbor --in-file transaction.broken
                  […]
                  a4  # map(4)
                      # key
                     65 66 69 6c 65 73  # text("files")
                      # value
                     81  # list(1)
                        a2  # map(2)
                            # key
                           69 6d 65 64 69 61 54 79 70 65  # text("mediaType")
                           […]
                            # key
                           63 73 72 63  # text("src")
                           […]
                      # key
                     65 69 6d 61 67 65  # text("image")
                     […]
                      # key
                     69 6d 65 64 69 61 54 79 70 65  # text("mediaType")
                     […]
                      # key
                     64 6e 61 6d 65  # text("name")
                     […]
```
4. Transform the transaction to be used with `cardano-hw-cli` by:
```
$ cardano-hw-cli transaction transform --tx-file transaction.broken --out-file transaction.canonical
```
5. Look at the canonical CBOR:
```
$ cardano-cli text-view decode-cbor --in-file transaction.canonical
                  […]
                  a4  # map(4)
                      # key
                     64 6e 61 6d 65  # text("name")
                     […]
                      # key
                     65 66 69 6c 65 73  # text("files")
                      # value
                     81  # list(1)
                        a2  # map(2)
                            # key
                           63 73 72 63  # text("src")
                           […]
                            # key
                           69 6d 65 64 69 61 54 79 70 65  # text("mediaType")
                           […]
                      # key
                     65 69 6d 61 67 65  # text("image")
                     […]
                      # key
                     69 6d 65 64 69 61 54 79 70 65  # text("mediaType")
                     […]
```
6. The metadata has been reordered canonically, leading to a hash mismatch that later leads to:
```
$ cardano-cli transaction submit --mainnet --tx-file transaction.signed
Command failed: transaction submit  Error: Error while submitting tx: ShelleyTxValidationError ShelleyBasedEraAlonzo
(ApplyTxError [UtxowFailure (WrappedShelleyEraFailure (ConflictingMetadataHash
(AuxiliaryDataHash {unsafeAuxiliaryDataHash = SafeHash "8dab3cc16767c49d79176ef8145c18c488a94faee7c12e1ce083b223529a134e"})
(AuxiliaryDataHash {unsafeAuxiliaryDataHash = SafeHash "f10e7d7f522f4f29184cedae42bf362b9b1155efd124468046f3309a9b4be4d0"})))])
```
7. Reorder the JSON to be in the canonical order in the first place:
```
           […]
                "name": "HeptaSean's Card",
                "files": [
                    {
                        "src": […],
                        "mediaType": "text/html"
                    }
                ],
                "image": […],
                "mediaType": "image/svg+xml"
           […]
```
8. `cardano-cli transaction build` produces the same, non-canonical order in the CBOR as before leaving no option to get to a transaction usable by `cardano-hw-cli` (other than using `--metadata-cbor-file` with a canonical binary CBOR).

**Expected behavior**
In the related issue https://github.com/input-output-hk/cardano-node/issues/2783, it is stated that `cardano-cli` does not *want* to produce canonical CBOR in https://github.com/input-output-hk/cardano-node/issues/2783#issuecomment-855904923.
But then the order should be taken *exactly* as in the given JSON file to be able to cater for `cardano-hw-cli` and similar tools manually.
This is also promised in https://github.com/input-output-hk/cardano-node/issues/2783#issuecomment-856008693, but it is clearly not the case, here.

**System info (please complete the following information):**
- OS Name: Arch Linux
- Node version 1.34.1
- CLI version  1.34.1

**Additional context**
* Issue on `cardano-hw-cli`: https://github.com/vacuumlabs/cardano-hw-cli/issues/130
* Detailed report, how I discovered this: https://forum.cardano.org/t/minting-an-on-chain-nft-with-a-hardware-wallet/105922?u=heptasean

**Comment by ross-spencer** [comment]
If I understand this issue to be about metadata ordering, then I am not seeing consistency either. If I create a dict for Pycardano as follows:

```
    tag = 674  #  transaction message/comment metadata
    tx_metadata = OrderedDict()
    tx_metadata["title"] = "Hello World! 🚀"
    tx_metadata["message"] = "You have successfully published Tx metadata!"
    tx_metadata["note"] = "Some more information about this Tx."
    tx_metadata["timestamp"] = f"{time.time()}"
    tx_metadata["1"] = "test 1"
    tx_metadata["3"] = "test 2"
    tx_metadata["2"] = "test 3"
```

Observe the cli output: `cardano-cli transaction view --tx-file tx_md.signed | jq .metadata`:

```

{
  "674": [
    [
      "title",
      "Hello World! 🚀"
    ],
    [
      "message",
      "You have successfully published Tx metadata!"
    ],
    [
      "note",
      "Some more information about this Tx."
    ],
    [
      "timestamp",
      "1710920747.6925607"
    ],
    [
      "1",
      "test 1"
    ],
    [
      "3",
      "test 2"
    ],
    [
      "2",
      "test 3"
    ]
  ]
}
```

On-chain:

```
{
   1: "test 1",
   2: "test 3",
   3: "test 2",
   title: "Hello World! 🚀",
   message: "You have successfully published Tx metadata!",
   note: "Some more information about this Tx.",
   timestamp: "1710920747.6925607"
}
```

see: [tx (bb9d3d9f9166476643739a47d39578ab50b6bcb53b2f209d485dab39e505e3a8)](https://preprod.cardanoscan.io/transaction/bb9d3d9f9166476643739a47d39578ab50b6bcb53b2f209d485dab39e505e3a8?tab=metadata).

Some predictability would be nice, but is there anything concrete anywhere that describes what users should expect? Even something saying data that lands on-chain is not expected to have any order?

**Comment by smelc** [comment]
cc @CarlosLopezDeLara

**Comment by ross-spencer** [comment]
In addition to above, what I am experiencing looks like a rendering issue on popular block-explorers with the underlying data looking okay, take for example the same data drawn from Kupo which looks like ordering is preserved:

```text
[{"hash":"8bad78c4b3cb2dd3cef2f0591bc992cb5e599a1414d407aee6e05c73d9f7530f","raw":"a11902a281a7657469746c657148656c6c6f20576f726c642120f09f9a80676d657373616765782c596f752068617665207375636365737366756c6c79207075626c6973686564205478206d6574616461746121646e6f74657824536f6d65206d6f726520696e666f726d6174696f6e2061626f757420746869732054782e6974696d657374616d7071313731303932323139392e383037333334613166746573742031613366746573742032613266746573742033","schema":{"674":{"list":[{"map":[{"k":{"string":"title"},"v":{"string":"Hello World! 🚀"}},{"k":{"string":"message"},"v":{"string":"You have successfully published Tx metadata!"}},{"k":{"string":"note"},"v":{"string":"Some more information about this Tx."}},{"k":{"string":"timestamp"},"v":{"string":"1710922199.807334"}},{"k":{"string":"1"},"v":{"string":"test 1"}},{"k":{"string":"3"},"v":{"string":"test 2"}},{"k":{"string":"2"},"v":{"string":"test 3"}}]}]}}}]
```

So I don't think this is the same problem my end.

**Comment by carbolymer** [comment]
In principle you should be able to use `--json-metadata-detailed-schema` switch to use a different (a bit more verbose) metadata schema. You'd have to prefix every field with one of the available types: `int`, `bytes`, `string`, `list` and encode maps as lists:
```json
{"0":
  {"map":
    [ { "k": {"string": "aaa"}
      , "v": {"string": "b4"}
      }
    , { "k": {"int": 1}
      , "v": {"string": "b6"}
      }
    , { "k": {"string": "aa"}
      , "v": {"string": "b2"}
      }
    , { "k": {"string": "ab"}
      , "v": {"string": "b3"}
      }
    , { "k": {"string": "b"}
      , "v": {"string": "b5"}
      }
    , { "k": {"string": "a"}
      , "v": {"string": "b1"}
      }
    ]
  }
}

```

I'm working on a fix which should canonicalise maps for CBOR.
