### ISSUE TITLE
bench-1: premature cluster termination

### ISSUE THREAD

**Issue by deepfire** [IntersectMBO/cardano-node#4385]
We've experienced a frequent premature termination while running node version `4e79695cb659db348129862708d2267f52ed1ca3` with ops version `67d168f926e8b1dd750863b982c2024bf13d2453`:  3 out of 8 runs had this.

Symptoms: the logs were cut short to roughly half the expected size.

The runs were:
- `2022-08-18-11.04.baseline.4e79.k51-5ep-360kTx-4000kU-1000kD-64kbs`
- `2022-08-18-18.45.baseline.4e79.k51-5ep-360kTx-4000kU-1000kD-64kbs`
- `2022-08-19-08.58.baseline.4e79.k51-5ep-360kTx-4000kU-1000kD-64kbs`

**Comment by deepfire** [comment]
Turned out, it is a `tx-generator` bug -- which we cannot really debug, until we integrate `cardano-tracer` into `cardano-ops`

**Comment by mgmeier** [comment]
Closing because:
* The ops cluster has been decomissioned, and the issue is not reproducible on the new Nomad cluster
* `cardano-tracer` has already been integrated into the new cluster
* The behaviour has not materialized again on any later node version
