### ISSUE TITLE
[FR] - Simplify p2p topology format

### ISSUE THREAD

**Issue by coot** [IntersectMBO/cardano-node#4559]
Currently the json format is more verbose than it needs to be, e.g.
```json
{
  "LocalRoots": {
    "groups": [
      { "localRoots":
        { "accessPoints":
            [ { "address": "35.180.225.101"
              , "port": 7776
              }
            ]
        , "advertise": false
        }
      , "valency": 3
      }
    ]
  }
, "PublicRoots": [
    { "publicRoots": {
        "accessPoints": [
          { "address": "relays-new.cardano-mainnet.iohk.io"
          , "port": 3001
          }
        ]
      , "advertise": false
      }
    }
  ]
, "useLedgerAfterSlot": 45000000
}
```

I suggest we simplify this to something like:
```json
{
  "localRoots": [
      { "accessPoints":
            [ { "address": "35.180.225.101"
              , "port": 7776
              }
            ]
      , "advertise": false
      , "valency": 1
      }
    ]
, "publicRoots": [
    { "accessPoints": [
          { "address": "relays-new.cardano-mainnet.iohk.io"
          , "port": 3001
          }
        ]
    , "advertise": false
    }
  ]
, "useLedgerAfterSlot": 45000000
}
```

Note: we ought to support both formats for a while; whenever we match the old format we should log a warning that this format will be only supported for next two major releases.

**Comment by gufmar** [comment]
looks good to me

**Comment by coot** [comment]
@CarlosLopezDeLara this is not a bug, I removed the `type: bug` label.

**Comment by coot** [comment]
I realised that the encoding could be slightly simplified.  I destructively updated the description of the issue. The gist is that `LocalRoots` can contain `accessPoints`, `advertise` and `valency` fields directly, without a need of extra object wrapper for `accessPoints` and `advertise` fields.

**Comment by coot** [comment]
Additional change: use `localRoots` and `publicRoots` instead of `LocalRoots` and `PublicRoots` - there's no need to leak Haskell naming convention of type constructors.
