### ISSUE TITLE
SPO Voting

### ISSUE THREAD

**Issue by Jimbo4350** [IntersectMBO/cardano-node#5602]
## SPO Voting

Test correct recording of SPO votes in the ledger (Y/N/A).  Correct total vote tallies.

### Implementation

* https://github.com/IntersectMBO/cardano-node/pull/5634
* https://github.com/IntersectMBO/cardano-node/pull/5821
* https://github.com/IntersectMBO/cardano-node/pull/5833
* https://github.com/IntersectMBO/cardano-node/pull/5870
* https://github.com/IntersectMBO/cardano-node/pull/5871

**Comment by smelc** [comment]
Unassigning myself because I'll be doing https://github.com/IntersectMBO/cardano-cli/issues/725 next and don't plan to do this one soon. Maybe @palas you want to look at it (there is one negative SPO voting test already)!?

**Comment by palas** [comment]
Still a PR to merge before closing
