### ISSUE TITLE
API Documentation Link Broken

### ISSUE THREAD

**Issue by ccgarant** [IntersectMBO/cardano-node#5651]
The API Documentation "here" like is broken. Get a 404 page error.

[edit by @smelc] This refers to https://cardano-node.cardano.intersectmbo.org/ being down

**Comment by smelc** [comment]
@disassembler> do we need a `cname` stanza in the [workflow here](https://github.com/IntersectMBO/cardano-node/blob/03fb7f78f8d8cffd3ea2151791dd8771184a52ae/.github/workflows/github-page.yml#L63) ([like on `cardano-cli`](https://github.com/IntersectMBO/cardano-cli/blob/3b70e39299b1279c690ec11cb5aec6c84e13eadc/.github/workflows/github-page.yml#L145))? cc @carbolymer
