### ISSUE TITLE
[BUG] - CardanoProtocolInstantiationPraosLeaderCredentialsError

### ISSUE THREAD

**Issue by AndrewWestberg** [IntersectMBO/cardano-node#5654]
**External**

**Area**
*SIGHUP*    Reloading configuration

**Summary**
In a testnet environment, I expect to be able to switch a block producer into a non-producing mode. I instead get an error reading credentials.

**Steps to reproduce**
1. Set up a block producer that uses the bulk-credentials option.
2. rename the bulk credentials json file to something else.
3. send a sighup to the node
4. Expect to see node operate in non-producing mode.
5. See error

```
{"app":[],"at":"2024-01-29T15:47:01.82Z","data":{"error":"CardanoProtocolInstantiationError (CardanoProtocolInstantiationPraosLeaderCredentialsError (CredentialsReadError \"/home/westbam/haskell/ppp/credentials.json\" /home/westbam/haskell/ppp/credentials.json: openBinaryFile: does not exist (No such file or directory)))","kind":"BlockForgingUpdateError"},"env":"8.7.3:24741","host":"clockwor","loc":null,"msg":"","ns":["cardano.node.startup"],"pid":"962629","sev":"Info","thread":"355"}
```

**Expected behavior**
I expect to see log information that disables block forging. Something like this:

```
pod_card:cardano.node.startup:Info:173] [2024-01-29 15:20:50.50 UTC] Performing block forging reconfiguration: Enabling block forging. To disable it please move/rename/remove the credentials files and then trigger reconfiguration via SIGHUP signal.
```

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version: 22.04
- Node version: 8.7.3

**Comment by bolt12** [comment]
Thank you @AndrewWestberg !

**Comment by AndrewWestberg** [comment]
@bolt12 This is low priority now as I've found a workaround by using a dummy credentials.json file.

```
mv credentials.json off-credentials.json
echo "[]" > credentials.json
kill -s HUP <pid>
```

**Comment by bolt12** [comment]
Thank you for letting me know!
