### ISSUE TITLE
Test CLI queries in a single integration test

### ISSUE THREAD

**Issue by smelc** [IntersectMBO/cardano-node#5672]
> So this is good but it should be a separate property where we potentially execute all of our cli queries in a single test.

_Originally posted by @Jimbo4350 in https://github.com/IntersectMBO/cardano-node/pull/5574#discussion_r1489754816_

**Comment by carbolymer** [comment]
Seems to be a duplicate of https://github.com/IntersectMBO/cardano-cli/issues/33. Feel free to close one or the other.

**Comment by smelc** [comment]
Fixed by https://github.com/IntersectMBO/cardano-node/pull/5684
