### ISSUE TITLE
Missing Doc Required by OSC Governance

### ISSUE THREAD

**Issue by Ranchhand87** [IntersectMBO/cardano-node#5874]
Please add CHANGELOG.md

 If Changelog already exists elsewhere, please add to main page of code and link accordingly. 

For Reference: https://intersect.gitbook.io/open-source-committee/policies/governance
Also see Documentation and Legal

**Comment by carbolymer** [comment]
`cardano-node` repository constists of multiple projects like `cardano-testnet` or `cardano-tracer` - each seems to have its own changelog in its subdirectory. This seems to align with the [policy](https://intersect.gitbook.io/open-source-committee/policies/documentation#recommended-documents), correct?

**Comment by Ranchhand87** [comment]
@carbolymer 

If there are CHANGELOG's please create a top level file and link accordingly.

**Comment by aleeusgr** [comment]
I'll take a look and open a PR soon.

**Comment by aleeusgr** [comment]
Sorry, omitted to add to my todo list and forgot, and remembered to double-check only last week. now I am nix-stuck: I need to add gpg signature to my nix settings and I failed to do so in home-manager. Hope to look at it today.

**Comment by aleeusgr** [comment]
Signed and pushed the commit.
