### ISSUE TITLE
[BUG] - ValueNotConservedUTxO

### ISSUE THREAD

**Issue by nikashitsa** [IntersectMBO/cardano-node#5876]
**External**

**Area**
Submitting transaction.

**Summary**
Trying to submit a transaction (mainnet) with 8 inputs and 2 outputs via blockfrost api, which uses cardano node.
Got this error message:
```
transaction submit error ShelleyTxValidationError ShelleyBasedEraBabbage (
  ApplyTxError
  [UtxowFailure (
    UtxoFailure
    (
    AlonzoInBabbageUtxoPredFailure
      (
        ValueNotConservedUTxO
        (MaryValue (Coin 4983251048)
          (MultiAsset (fromList
          [(PolicyID {policyID = ScriptHash \"23c9b05ee16199b4955f7c491c887b9bd53d77a4af65105c54fe13eb\"},
          fromList [(\"53756e6461655265776172645469636b65743234\",1)]),
          (PolicyID {policyID = ScriptHash \"e4bbbaa875a797578044ef27713d23dfe07ce74f33163e7c40d7f480\"},
          fromList [(\"544d494e\",1)])]))
        )
        (
          MaryValue (Coin 4983251048)
          (MultiAsset (fromList []))
        )
      )
    )
  )]
)
```

`MaryValue (Coin 4983251048)` is the same. What could be the reason of this error?

Value is conserved. Isn't it?

**Expected behavior**
Successful transaction.

**Comment by HeinrichApfelmus** [comment]
This is likely a user error — specifically, the transaction consumes two tokens of quantity 1, but does not produce them. These tokens need to be added to the transaction outputs, or burned in the `mint` field.
