### ISSUE TITLE
node 8.12-pre - new metric `build_info` not returning valid json data

### ISSUE THREAD

**Issue by gitmachtl** [IntersectMBO/cardano-node#5881]
```console
$ cardano-node8 version
cardano-node 8.12.0 - linux-x86_64 - ghc-8.10
git rev ae8bc933ee6b6366c04854c1e127fd8dfb29b556
``` 

the new metric `build_info` returns pseudo json data. would be nice if its valid json data.

```console
curl -s http://127.0.0.1:13798/metrics | grep build_info
cardano_node_metrics_cardano_build_info {version_major="8",version_minor="12",version_patch="0",version="8.12.0",revision="ae8bc933ee6b6366c04854c1e127fd8dfb29b556",compiler_name="ghc",compiler_version="8.10",compiler_version_major="8",compiler_version_minor="10",architecture="x86_64",os_name="linux"} 1
```

it also returns two values, the pseudo-json and the value `1`

**Comment by mgmeier** [comment]
This metric provides build info in according to the OpenMetrics specification. There are 2 common ways to expose all that info:
1. A `LabelSet` with a metric of constant value (which was chosen)
2. A list of `Metric`s of type `Info`

The option to have one single `Info` metric with a complete JSON rendering defies the purpose of clients to easily select / query from a time series of expositions, using the build info as query filters - without having to parse any JSON.

cf. https://github.com/prometheus/OpenMetrics/blob/main/specification/OpenMetrics.md
