### ISSUE TITLE
[FR] - Support aarch64-linux in Nix Flake

### ISSUE THREAD

**Issue by sempruijs** [IntersectMBO/cardano-node#5890]
External

**Area**
Regarding the build system outputs

**Describe the feature you'd like**
I would like to build cardano-cli on aarch64-linux via the nix flake.
I use aarch64-linux in a virtual machine on my mac and raspberry pi is also aarch64-linux.
Here's what I would like to do:
```shell
nix build github:intersectmbo/cardano-node#packages.aarch64-linux.cardano-cli
```

**Describe alternatives you've considered**

I think you can build it on aarch64-linux but as far I know not via the nix flake.
If I'm missing something please let me know.

**Comment by smelc** [comment]
@sempruijs> FYI if you wanted to do that on the `cardano-cli` repo, it would look like this (here for `aarch64-darwin`, since `aarch64-linux` is not supported):

```shell
nix build github:intersectmbo/cardano-cli#hydraJobs.aarch64-darwin.packages.cardano-cli:exe:cardano-cli
```

I don't know the target's name for the same binary on `cardano-node` though. Probably @angerman knows.

**Comment by sempruijs** [comment]
Hmm intresting. I thought that cardano-cli development also took place in this repo. Why is there a defferent repo? Should I place this issue there?
Yes aarch64-darwin seems to be support, I think it would be cool to support aarch64-linux too.
