### ISSUE TITLE
[BUG] - cardano-node 9.0.0 is missing conway-genesis.json

### ISSUE THREAD

**Issue by den-is** [IntersectMBO/cardano-node#5901]
*External*

web-page https://book.play.dev.cardano.org/advanced.html
and release artifact
https://github.com/IntersectMBO/cardano-node/releases/download/9.0.0/cardano-node-9.0.0-linux.tar.gz

are missing `conway-genesis.json`

**Comment by disassembler** [comment]
It's a feature not a bug. It allows a release that can be integrated by downstream components without having the genesis file finalized. Responding to SPO feedback about needing a dummy genesis on mainnet we altered the behavior so the node behaved as an 8.x node at the hard fork of the genesis file doesn't exist in the 8.12 release.
