### ISSUE TITLE
[FR] - Why are there no new versions of cardano-testnet in CHAP?

### ISSUE THREAD

**Issue by zlonast** [IntersectMBO/cardano-node#5913]
External

**Describe the feature you'd like**
Return package releases to CHAP? [issues830](https://github.com/IntersectMBO/cardano-haskell-packages/issues/830)

**Comment by carbolymer** [comment]
Thanks for the reminder, will do!

**Comment by carbolymer** [comment]
https://chap.intersectmbo.org/package/cardano-testnet-9.0.0/
