### ISSUE TITLE
[FR] - Conway support in `cardano-testnet`

### ISSUE THREAD

**Issue by euonymos** [IntersectMBO/cardano-node#5922]
External / cardano-testnet

Please add support for the Conway era to the `cardano-testnet` component.

**Comment by carbolymer** [comment]
Can you elaborate what do you mean here? Cardano Testnet supports Conway era. What error do you see?

**Comment by errfrom** [comment]
@carbolymer It seems there is no CLI flag to run `cardano-testnet` in the Conway era

**Comment by euonymos** [comment]
Thanks!
