### ISSUE TITLE
[FR] - Auto load snapshot with mithril-client 

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [IntersectMBO/cardano-node#5931]
**Internal/External**
*Internal*   

**Area**
Deployment

**Describe the feature you'd like**
To speed up cardano-node initial setup time it would be great if `mithril-client` could be bundled as part of OCI image and ideally would auto-load the required snapshot

**Why mithril-client?**
Seems to be faster than usual snapshot loading and supports other networks

**Describe alternatives you've considered**
There were some instances where we had to do it, we have a shell script for that, it just would be nice if it was all automated

**Comment by disassembler** [comment]
This would put a dependency of mithril on the node repository. Closing as we are not willing to add that as a dependency to this repository.
