### ISSUE TITLE
[BUG] - `syncProgress` incorrectly says as `100.00` for Preview network (node 9.1.0)

### ISSUE THREAD

**Issue by sourabhxyz** [IntersectMBO/cardano-node#5940]
*External*

**Area**
`cardano-node`

**Summary**
`syncProgress` incorrectly says as `100.00` for Preview network (node 9.1.0) when querying for tip even when it is not, see below response:
```
❯ cardano-cli query tip --testnet-magic 2 --socket-path ~/cardano-nets/preview/db/node.socket
{
    "block": 120020,
    "epoch": 29,
    "era": "Babbage",
    "hash": "a576fb4e48804bfb67f213a5dbc8554afa532b1b5f865e13e4ba364f095b5a7c",
    "slot": 2537607,
    "slotInEpoch": 32007,
    "slotsToEpochEnd": 54393,
    "syncProgress": "100.00"
}   
```
At the time of writing this issue, preview is on block 2359827.

**Steps to reproduce**
1. Spin up cardano-node v9.1.0 with [provided](https://book.play.dev.cardano.org/env-preview.html) configuration from fresh start.
2. Query for tip.
3. See that it immediately gives `syncProgress` as `100.00`.

**Expected behavior**

`syncProgress` should indicate actual sync progress.

**System info (please complete the following information):**
- OS Name: MacOS
- OS Version: Sonoma 14.5
- Node version (output of `cardano-node --version`): 
  ```
  cardano-node 9.1.0 - darwin-aarch64 - ghc-9.6
  git rev 0000000000000000000000000000000000000000
  ```
  I can pull out exact git revision, if desired, but it should be `9.1.0` tag.
- CLI version  (output of `cardano-cli --version`)
  ```
  cardano-cli 9.2.1.0 - darwin-aarch64 - ghc-9.6
  git rev 2fd3e13e9fa48a404429fd28252cecd723e021d5
  ```

**Comment by carbolymer** [comment]
Fixed in https://github.com/IntersectMBO/cardano-cli/pull/851
