### ISSUE TITLE
[BUG] - `cardano-testnet`: `--max-lovelace-supply` has no effect

### ISSUE THREAD

**Issue by errfrom** [IntersectMBO/cardano-node#5953]
External / cardano-testnet

Specifying a value for the `--max-lovelace-supply` command line option does not affect the generated Shelley genesis configuration.
Indeed, the total supply is hardcoded to 2 trillion Lovelace, while the value from the passed `shelleyGenesis` is ignored.
https://github.com/IntersectMBO/cardano-node/blob/67c9dc53620b391d0fb2563ff2fcbe3252a77d62/cardano-testnet/src/Testnet/Components/Configuration.hs#L184

**Comment by carbolymer** [comment]
cc @smelc

**Comment by smelc** [comment]
@errfrom> would you be able to test a fix if it's on a PR of `cardano-node`? In other words: would you be able to test a fix before it is included in a release of `cardano-node`)?

**Comment by errfrom** [comment]
@smelc most likely yes
