### ISSUE TITLE
[FR] - cardano-testnet: set minFeeRefScriptCostPerByte to non-zero

### ISSUE THREAD

**Issue by klntsky** [IntersectMBO/cardano-node#5965]
**External**

**Area**
*Other*   

**Describe the feature you'd like**
To test the new fee structure, we need to ensure that the protocol parameter for the reference script fees per byte is not zero (for the fees to be different). 

https://github.com/IntersectMBO/cardano-node/blob/fecf2bf0c728060c0ff408d2a7fecc152c25dd4f/cardano-testnet/files/data/conway/genesis.conway.spec.json#L27

**Comment by carbolymer** [comment]
Can you add more description to this issue? Is the desired feature to change the default or to have it configurable?

**Comment by klntsky** [comment]
@carbolymer to change the default in the genesis to a non-zero value

**Comment by carbolymer** [comment]
cc: @CarlosLopezDeLara @smelc

**Comment by CarlosLopezDeLara** [comment]
I agree, unless there is any important reason for having the cost models set to zero (i.e. testing), it would be a good idea to default to the current Mainnet cost models.
