### ISSUE TITLE
[BUG] - Version 9.1.1 required full replay on mainnet restart from version 9.1.0

### ISSUE THREAD

**Issue by cryptophonic** [IntersectMBO/cardano-node#5971]
**External**

**Area**
*Other*   Full replay on mainnet bug not fixed with 9.1.1

**Summary**
We just restarted a relay node on mainnet, upgrading to cardano-node version 9.1.1, post-conway, where the previously running cardano-node version was 9.1.0 at the time the restart was triggered.  At the time of restart, the running cardano-node version 9.1.0 was stable with 58 incoming peers and 60 outgoing peers.  On restart, version 9.1.1 triggered a full replay so it appears 9.1.1 did not fix the intended bug, for this particular restart.  Haven't tried yet on our other relays. 

Our systemd script is well tested at this point, it does use SIGINT for restart and has worked correctly for years on other minor upgrades that do not require full replays.

Previous version:

```
$ ./9.1.0/cardano-node --version
cardano-node 9.1.0 - linux-x86_64 - ghc-8.10
git rev 176f99e51155cb3eaa0711db1c3c969d67438958
```

Upgrade version:

```
$ cardano-node --version
cardano-node 9.1.1 - linux-x86_64 - ghc-8.10
git rev efd560070aaf042d1eb4680ae37fc607c7742319
```

Relevant logs (UTC time):

```
Sep 03 15:26:14 cardano6 start-cardano-node.sh[2268459]: [cardano6:cardano.node.basicInfo.protocol:Notice:9] [2024-09-03 15:26:14.73 UTC] Byron; Shelley
Sep 03 15:26:14 cardano6 start-cardano-node.sh[2268459]: [cardano6:cardano.node.basicInfo.version:Notice:9] [2024-09-03 15:26:14.73 UTC] 9.1.1
Sep 03 15:26:14 cardano6 start-cardano-node.sh[2268459]: [cardano6:cardano.node.basicInfo.commit:Notice:9] [2024-09-03 15:26:14.73 UTC] efd560070aaf042d1eb4680ae37fc607c7742319

...

Sep 03 15:27:57 cardano6 start-cardano-node.sh[2268459]: [cardano6:cardano.node.ChainDB:Error:9] [2024-09-03 15:27:57.42 UTC] Invalid snapshot DiskSnapshot {dsNumber = 133765893, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 2123214917 "expected word16"))
Sep 03 15:29:32 cardano6 start-cardano-node.sh[2268459]: [cardano6:cardano.node.ChainDB:Error:9] [2024-09-03 15:29:32.24 UTC] Invalid snapshot DiskSnapshot {dsNumber = 133760634, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 2123217713 "expected word16"))
```

**Steps to reproduce**
1. Replace version 9.1.0 with 9.1.1
2. Trigger a node restart

**Expected behavior**
A quicker restart not requiring a full replay

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 22.04.3 LTS
- Node version 9.1.1
- CLI version  Not related, but 9.2.1.0

**Comment by kderme** [comment]
Has replaying from genesis resolved the issue, can new Conway snapshots be parsed?

**Comment by lehins** [comment]
How was the `cardano-node` executable acquired?  Was the executable downloaded from the [`cardano-node-9.1.1` release page](https://github.com/IntersectMBO/cardano-node/releases/tag/9.1.1) or was it built from source?

If latter is the case, then was `nix` used or was it built using plain old `cabal`?

**Comment by cryptophonic** [comment]
It was build from source, using cabal.  I wonder if that's the difference.  Checking on whether it works after replaying by rebooting again now.

**Comment by cryptophonic** [comment]
Rebooting a second time (9.1.1 -> 9.1.1, same executable) and it's failing the snapshot and replaying from genesis again.  I will try downloading a release next; it will take several hours to come back up

Sep 04 19:41:10 cardano6 start-cardano-node.sh[2280681]: [cardano6:cardano.node.ChainDB:Error:9] [2024-09-04 19:41:10.47 UTC] Invalid snapshot DiskSnapshot {dsNumber = 133867461, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 2122344599 "expected word16"))
Sep 04 19:42:48 cardano6 start-cardano-node.sh[2280681]: [cardano6:cardano.node.ChainDB:Error:9] [2024-09-04 19:42:48.97 UTC] Invalid snapshot DiskSnapshot {dsNumber = 133863223, dsSuffix = Nothing}InitFailureRead (ReadFailed (DeserialiseFailure 2122316074 "expected word16"))

**Comment by lehins** [comment]
@cryptophonic Make sure you run `cabal update` before building it

**Comment by lehins** [comment]
The reason for this is if you don't have the new version of `cardano-ledger-shelley-1.12.3.0` that contains the fix, you will build a version of the node that will be identical to `cardano-node-9.1.0`

**Comment by lehins** [comment]
You can confirm the version of the package being used when you build your node this way:
```shell
$ cat dist-newstyle/cache/plan.json | jq '.["install-plan"][].id' | grep cardano-ledger-shelley-1
``` 
If you get `cardano-ledger-shelley-1.12.2.0`, then it is expected that you are having this issue.

**Comment by cryptophonic** [comment]
Indeed.  That is the problem here.  Thanks, I will close the issue.
