### ISSUE TITLE
[BUG] - unable to start cardano node 9.2.1

### ISSUE THREAD

**Issue by AdamMachera** [IntersectMBO/cardano-node#6018]
**Internal/External**
*External* 

**Area**
*Other*   Unable to start node

**Summary**
When we try to run cardano-node version 9.x in docker container or as standalone process it keeps crashing on synchronization
[https://forum.cardano.org/t/cardano-node-9-2-1-crashes-in-ubuntu-without-any-error-code/136469](cardano forum)

this is how we start the standalone cardano node:
`sudo /datadrive/bin/bin/cardano-node run --topology /datadrive/config/topology.json  --database-path /datadrive/node-db --config /datadrive/config/config-bp.json --port 3001 --socket-path /datadrive/node-ipc/node.socket >>/datadrive/logs/node.log 2>&1 &`

Not sure how we can enable more diagnostics to check why it is failing.
Currently it is crashing on this line
[cardano-:cardano.node.ChainDB:Info:5] [2024-09-29 19:31:21.54 UTC] Pushing ledger state for block b7ea3550ce8ca8b0df44d835e69466e16506e341b21e11b427a125f59df6292f at slot 98236145. Progres s: 57.40%

when we run it as docker container, the container at synchronization keeps restarting.
We didn't experience such problems with version 8.x of cardano and it worked without any issues

**Expected behavior**
Cardano node is up and running

**System info (please complete the following information):**
- OS Name: Ubuntu
- OS Version 20.04
- Node version 9.2.1

**Comment by carbolymer** [comment]
Can you post the full log? Have you verified that you're not running out of RAM and your OS isn't OOM-killing the process?

**Comment by AdamMachera** [comment]
I think it was related to having not enough memory, version 8.1.2 was able to run node with 16gb on ubuntu. Once I changed the memory to 32gb it started going further in synchronization process.
[node.log](https://github.com/user-attachments/files/17478729/node.log)
