### ISSUE TITLE
[FR] - Ability to validate transaction without submission

### ISSUE THREAD

**Issue by frog357** [IntersectMBO/cardano-node#6060]
**Internal/External**
*External*   otherwise.

**Area**
*Other*   Any other topic (Delegation, Ranking, ...).

**Describe the feature you'd like**
I would like to see the ability to validate a transaction before I submit it. Having a flag that would perform all the same checks as cardano-cli transaction submit but without the submit part.

**Additional context / screenshots**
It might be fringe and unneeded but the thought came to me when building a large transaction with more than 100 outputs, I was thinking it would be nice to know if this transaction is hitting the transaction size limits. Maybe something like a flag:
cardano-cli transaction validate --tx-file infile --mainnet

**Comment by carbolymer** [comment]
This is `cardano-cli` related. Can you open an  issue in https://github.com/IntersectMBO/cardano-cli/ repo, pleease?
